name: large-records-plugin

dependencies:
  - base >=4.13 && <4.15

library:
  source-dirs: src
  other-modules: []
  dependencies:
    - ghc
    - containers
    - uniplate
    - vector
    - large-records
    - record-hasfield
    - sop-core

tests:
  large-records-plugin-tests:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - large-records-plugin
      - record-dot-preprocessor
      - record-hasfield
